favicon: null
name: taeo
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6288937
  brandStrength: 0.5719656
  lightness: 0.8877551
  brandColors:
    - '#191818'
    - '#5C4130'
    - '#FEFEFD'
    - '#BC895C'
    - '#E9BE88'
  rhythmicContrast: 0.4941959
typography_spectrum: 0.3764769
layout_spectrum: 0.4291085
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
